spring.datasource.url=jdbc:postgresql://localhost:7433/cdoc2auth
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver

app.smartid.client.hostUrl=https://sid.demo.sk.ee/smart-id-rp/v3/

spring.ssl.bundle.jks.sid-trusted-issuers.truststore.location=classpath:demo_server_trusted_ssl_certs.jks
spring.ssl.bundle.jks.sid-trusted-issuers.truststore.password=changeit
spring.ssl.bundle.jks.sid-trusted-issuers.truststore.type=jks

app.well-known.ec-private-key-name=ec-es256-private.pem
app.well-known.ec-key-kid=ec-key-2026

app.rp.name=DEMO
app.rp.uuid=00000000-0000-4000-8000-000000000000
